- name: fix a little problem
  shell: "apt-get update"

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present

- name: Nginx | Make sure the Nginx configuration is updated
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx